<?php
// $Id$

/**
 * @file
 *  OKHUB API Module.
 *
 * This module uses the OKHUB Knowldege Services API (http://developer.okhub.org/hub-api-documentation/api-explorer) in order
 * to search, display and import data and metadata contained in the OKHUB
 * datasets, which are maintained by the OKHUB.
 */

/* --------------------- Hooks implementations -------------------- */

/**
 * Include files that implement the request and objects classes
 */
require_once('okhubapi.default.inc');
require_once(OKHUB_API_LIBRARY_PATH . 'okhubwrapper.default.inc');

/**
 * Implements hook_flush_caches().
 */
function okhubapi_flush_caches() {
  return array(OKHUB_API_CACHE_REQUESTS);
}

/**
 * Implements hook_enable().
 */
function okhubapi_enable() {
    drupal_flush_all_caches();
    drupal_set_message(t('To use the OKHUB API module, first go to the <a href="@url">OKHUB API Administration</a> to set general parameters, including your OKHUB API key.', array('@url' => url('admin/config/services/okhubapi'))));
}

/**
 * Implements hook_disable().
 */
function okhubapi_disable() {
    drupal_flush_all_caches();
}

/**
 * Implements of hook_menu().
 */
function okhubapi_menu() {
  $items = array();

  $items['admin/config/services/okhubapi'] = array(
    'title' => t('OKHUB API Module settings'),
    'description' => t('Global settings for the OKHUB API module.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('okhubapi_settings_form'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer okhubapi'),
    'file' => 'okhubapi.admin.inc',
  );
  
  return $items;
}

/**
 * Implements hook_permission().
 */
function okhubapi_permission() {
  return array(
    'administer okhubapi' => array(
      'title' => t('Administer the OKHUB API module'), 
      'description' => t('Perform administration tasks for the OKHUB API module.'),
    ),
  );
}
 
/**
 * Implements hook_help().
 */
function okhubapi_help($path, $arg) {
  if ($path == 'admin/help#okhubapi') {
    return t('Uses the OKHUB API to provide access to Eldis and Bridge content. API documentation: ') . OKHUB_API_DOCUMENTATION_URL;
  }
}

/**
 * Function used to retrieve OKHUB items using get_all.
 */
function okhubapi_get_all($type, $set, $format) {
  $okhubwrapper = new OkhubApiWrapper;
  $api_key = variable_get('okhubapi_api_key', '');
  $priorities = _okhubapi_get_priorities_arr();
  $response = $okhubwrapper->getAll($type, $set, $api_key, $format, $priorities);
  return $response;
}

/**
 * Function used to retrieve OKHUB items using search, with parameters.
 */
function okhubapi_search($type, $set, $format, $params, $extra_fields = array()) {
  $okhubwrapper = new OkhubApiWrapper;
  $api_key = variable_get('okhubapi_api_key', '');
  $priorities = _okhubapi_get_priorities_arr();
  $response = $okhubwrapper->search($type, $set, $api_key, $format, 0, 0, 0, $params, $extra_fields, $priorities);
  return $response;
}

/**
 * Function used to retrieve OKHUB items using count, with parameters.
 */
function okhubapi_count($type, $set, $count_category, $age_results = 0, $params = array()) {
  $okhubwrapper = new OkhubApiWrapper;
  $api_key = variable_get('okhubapi_api_key', '');
  $priorities = _okhubapi_get_priorities_arr();
  $response = $okhubwrapper->count($type, $set, $api_key, $count_category, $age_results, $params, $priorities);
  return $response;	
}

/* ---------------- Examples of calls to the OKHUB API --------------- */

/**
 * Implements hook_block_info().
 */
function okhubapi_block_info() {
  $blocks = array();
  $blocks['okhubapi_eldis_documents'] = array(
    'info' => t('Eldis documents'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['okhubapi_eldis_organisations'] = array(
    'info' => t('Eldis organisations'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['okhubapi_bridge_documents'] = array(
    'info' => t('Bridge documents'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function okhubapi_block_view($block_name = '') {
  $block = array();
  $content = '';

  // Retrieves latest Eldis documents
  if ($block_name == 'okhubapi_latest_eldis_documents') {
    $response = okhubapi_get_all('documents', 'eldis', 'full');
    $items = $response->getArrayLinks();
    if (is_array($items)) {
      $theme_args = array('items' => $items, 'type' => 'ol');
      $content = theme('item_list', $theme_args);
    }
    else  {
      $content = theme('help', 'Error when recovering block content.');
    }
    $block['subject'] = t('Eldis recent documents');
  }
  
  // Retrieves latest Eldis organisations
  if ($block_name == 'okhubapi_latest_eldis_organisations') {
    $response = okhubapi_get_all('organisations', 'eldis', 'full');
    $items = $response->getArrayLinks();
    if (is_array($items)) {
      $theme_args = array('items' => $items, 'type' => 'ol');
      $content = theme('item_list', $theme_args);
    }
    else  {
      $content = theme('help', 'Error when recovering block content.');
    }
    $block['subject'] = t('Eldis latest organisations');
  }
  
    // Retrieves latest Bridge documents
  if ($block_name == 'okhubapi_latest_bridge_documents') {
    $response = okhubapi_get_all('documents', 'bridge', 'full');
    $items = $response->getArrayLinks();
    if (is_array($items)) {
      $theme_args = array('items' => $items, 'type' => 'ol');
      $content = theme('item_list', $theme_args);
    }
    else  {
      $content = theme('help', 'Error when recovering block content.');
    }
    $block['subject'] = t('Bridge latest documents');
  }
  $block['content'] = $content;
  return $block;
}

/*
 * Function to return the selected datasources as array
 */
function _okhubapi_get_selected_datasources_array(){
	$datasources_arr = array();
    if ($datasources = variable_get('okhubimport_default_datasources')) {
    	foreach($datasources as $datasource => $value){
    		if($value){
    			$datasources_arr[] = $datasource;
    		}
    	}
    }
    return $datasources_arr;
}

/*
 * Function to return the selected datasources as a string for passing to setParam with sources attribute
 */
function _okhubapi_get_datasources_param(){
	$datasources_param = '';
    if ($datasources = _okhubapi_get_selected_datasources_array()) {
    	foreach($datasources as $datasource){
    		if($datasources_param){
    			$datasources_param .= '|';
    		}
    		$datasources_param .= $datasource;
    	}
    }
    return $datasources_param;
}

/**
 * Get array of sources for form.
 */
function _okhubapi_get_sources_options(){
	global $language;
    $sources_response = okhubapi_get_all('sources', 'hub', 'full');
    $sources_options = array();
    if(isset($sources_response->results)){
	    foreach($sources_response->results as $source){
	    	$is_semantic = FALSE;
    		if($source->get_value('is_semantic')){
    			$is_semantic = TRUE;
    		}
	    	if($source->get_value('code') && $source->get_value('name') && !$is_semantic){
	    		$sources_options[$source->get_value('code')] = $source->get_value('name');
	    	}
	    }
    }
 	return $sources_options;
}

/**
 * Get array of all themes (or for only for selected datasources) for form.
 */
function _okhubapi_get_themes_arr($selected_datasources_only = FALSE){
	global $language;
	$params = array();
	if($selected_datasources_only){
		$datasources = _okhubapi_get_datasources_param();
		$params['source'] = $datasources;
	}
    $themes_response = okhubapi_search('themes', 'hub', 'full', $params);
    $theme_arr = array();
    if(isset($themes_response->results)){
	    foreach($themes_response->results as $theme){
	    	if(isset($theme->object_id) && isset($theme->title)){
	    		$theme_arr[$theme->object_id['hub']] = $theme;
	    	}
	    }
    }
 	return $theme_arr;
}


/**
 * Get theme options for form
 */
function _okhubapi_get_themes_options($theme_arr){
	$themes_options = array();
	foreach($theme_arr as $theme){
		$default_theme_title = '';
		$lang_title_arr = array();
	    foreach($theme->title as $title_arr){
	    	foreach($title_arr as $lang => $title){
	    		$built_title = $title[0] . ' [' . $lang . ']';
    			if(!in_array($built_title, $lang_title_arr)){
    				$lang_title_arr[] = $built_title;
    			}
    		}
    	}
	   	foreach($lang_title_arr as $title){
    		if($default_theme_title) {
    			$default_theme_title .= ' | ';
    		}
    		$default_theme_title .= $title;
    	}
    	if($default_theme_title){
    		$themes_options[$theme->object_id['hub']] = $default_theme_title;
    	} 
    }
 	return $themes_options;
}

/*
 * Prepare a list of available languages from the 
 */
function _okhubapi_get_language_options_from_themes($theme_options){
	$language_options = array('all' => 'All');
	foreach($theme_options as $theme_arr){
		foreach($theme_arr->title as $source => $source_theme_arr){
			foreach($source_theme_arr as $lang_key => $value){
				$language_options[$lang_key] = $lang_key;
			}
		}
	}
	return $language_options;
}


/**
 * Get array of all languages for form.
 */
function _okhubapi_get_all_languages_arr(){
    $languages_response = okhubapi_count('documents', 'hub', 'language');
    $language_arr = array();
    if(isset($languages_response->results)){
	    foreach($languages_response->results as $language){
	    	if($language_name = $language->get_value('object_name')){
	    		$language_arr[$language_name] = $language_name;
	    	}
	    }
    }
 	return $language_arr;
}

/**
 * Get array of priorities for requests (datasource and language)
 */
function _okhubapi_get_priorities_arr(){
    $priorities = array();
    $priorities['priority_datasource'] = variable_get('okhubimport_priority_datasource', '');
    $priorities['priority_language'] = variable_get('okhubimport_priority_language', '');
 	return $priorities;
}

